language: php

php:
  - 5.2
  - 5.3

branches:
  only:
    - master
    - development

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential libpcre3-dev php-pear php5-curl php5-imagick
  - sudo pecl install oauth
  - sudo pear channel-discover pear.bovigo.org
  - sudo pear install bovigo/vfsStream-beta

script: phpunit -v --configuration src/tests/phpunit.xml src/tests/
